# Generated by Django 4.1.6 on 2023-02-10 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=20)),
                ('societe', models.CharField(max_length=250)),
                ('statut', models.CharField(choices=[('Prospect', 'Prospect'), ('Client', 'Client')], max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_maj', models.DateField(auto_now=True)),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouvert', models.BooleanField(default=True)),
                ('signe', models.BooleanField(default=False)),
                ('date_signature', models.DateField()),
                ('montant', models.FloatField()),
                ('echeance', models.DateField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_maj', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouvert', models.BooleanField(default=True)),
                ('date_evenement', models.DateField()),
                ('participants', models.PositiveIntegerField()),
                ('notes', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_maj', models.DateField(auto_now=True)),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.contrat')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
