# Generated by Django 4.1.6 on 2023-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
