# Generated by Django 4.1.6 on 2023-02-28 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_contrat_date_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='support',
            field=models.ForeignKey(limit_choices_to={'groups': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
