# Generated by Django 4.1.6 on 2023-02-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='username',
        ),
        migrations.AddField(
            model_name='personnel',
            name='equipe',
            field=models.CharField(choices=[('GESTION', 'Gestion'), ('VENTE', 'Vente'), ('SUPPORT', 'Support')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
