# Generated by Django 4.1.6 on 2023-02-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('connexion', '0004_alter_personnel_managers_alter_personnel_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='groups',
        ),
        migrations.AddField(
            model_name='personnel',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
