# Generated by Django 4.1.6 on 2023-02-16 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('connexion', '0005_remove_personnel_equipe_remove_personnel_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to='auth.group'),
        ),
    ]
